"""empty message

Revision ID: b67f309aeb33
Revises: 9c966c35c3c7
Create Date: 2023-03-20 23:51:11.336175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67f309aeb33'
down_revision = '9c966c35c3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('pages', sa.String(length=20), nullable=True),
    sa.Column('ISBN', sa.String(length=200), nullable=True),
    sa.Column('cover', sa.String(length=20), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('car')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('serial', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], name='car_user_token_fkey'),
    sa.PrimaryKeyConstraint('id', name='car_pkey')
    )
    op.drop_table('book')
    # ### end Alembic commands ###
